#-------------------------------
# Site Settings
title: Abla Analytics | Mesure d'audience alternative à Google Analytics
logo: 'https://test2.abla.io/img/logo-abla.svg'
descri ption: Le blog sur la conformité RGPD des cookies
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://test2.abla.io" # the base hostname & protocol for your site, e.g. http://example.com
color_scheme: auto # You can choose three modes auto, light, and dark. By default, the auto mode is set, which means the user can choose the light or dark mode themself.


#-------------------------------
# Author Settings
authors:
  sal:
    name: Caroline
    display_name: Caroline
    avatar: 'https://test2.abla.io/img/logo-abla.svg'
    email: wowthemesnet@gmail.com
    web: https://www.wowthemes.net/donate/
    twitter: https://twitter.com/wowthemesnet
    description: "Author of Memoirs, a Bootstrap Medium styled template available for Jekyll. You are currently previewing Jekyll template demo."
  john:
    name: John
    display_name: John
    avatar: 'assets/images/avatar.png'
    email: wowthemesnet@gmail.com
    web: https://www.wowthemes.net
    twitter: https://twitter.com/wowthemesnet
    description: "Write a short description of the author here. You are currently previewing Memoirs demo, a Jekyll template compatible with Github pages."


social:
- {icon: "ion-logo-twitter", link: "https://twitter.com/ablaanalytics"}
- {icon: "ion-logo-facebook", link: "https://facebook.com/ablaanalytics"}
- {icon: "ion-logo-instagram", link: "https://instagram.com/ablaanalytics"}
- {icon: "ion-logo-linkedin", link: "https://linkedin.com/company/ablaanalytics"}

#-------------------------------
# Hero Settings
hero:
  hero__title: L’analytics différemment
  hero__description: Abla c’est simplement une solution de mesure d'audience pour les sites internet. Notre différence avec Google Analytics ? On est respectueux par défaut au RGPD et aux recommandations de la CNIL.
  hero__image: '../images/google-analytics-alternative-rgpd.jpg'


#-------------------------------
# Newsletter
mailchimp: enable # To enable the mailchimp form, use the value 'enable'. To disable the form, leave the field blank.
mailchimp__identifier: frnla.us6.list-manage.com/subscribe/post?u=6314d69a3f315af7ce3fb00a0&amp;id=3038727cc3 # Add your MailChimp form identifier. For example - frnla.us6.list-manage.com/subscribe/post?u=6314d69a3f315af7ce3fb00a0&amp;id=3038727cc3
mailchimp__input__text: Abonnez-vous ici
mailchimp__button__text: Obtenez un nouveau pourboire


#-------------------------------
# Gallery Footer Section
gallery:
  gallery__title: Galerie
  gallery__columns: 3
  gallery__images:
    - alt: 'Rest'
      url: '/images/100.jpg'
    - alt: 'Lifestyle'
      url: '/images/101.jpg'
    - alt: 'Hobby'
      url: '/images/102.jpg'
    - alt: 'Notes'
      url: '/images/103.jpg'
    - alt: 'Rest'
      url: '/images/104.jpg'
    - alt: 'Hobby'
      url: '/images/105.jpg'
    - alt: 'Fashion'
      url: '/images/106.jpg'
    - alt: 'Notes'
      url: '/images/107.jpg'
    - alt: 'Rest'
      url: '/images/108.jpg'


#-------------------------------
# Contact Settings
contact:
  email: bonjour@abla.io # Add your email for contant form
  description: Menso comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want. # Add a description of your form

# NOTE
# Menso theme comes with a contact form built-in. You can use this form with Formspree (https://formspree.io/) service and get up to 50 submissions for free. Also, you can easily switch to another service if you want.




#-------------------------------
# Google Analytics
google-analytics: # Add your GA Tracking Id


#-------------------------------
# Build Settings
markdown: kramdown
permalink: /:title
plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 9
paginate_path: "/blog/page:num/"

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext


include:
  - _pages

sass:
  sass_dir: _sass
  style: compressed



  date_format: "%A %e %B %Y"
